group_imports = "StdExternalCrate"
imports_layout = "HorizontalVertical"
indent_style = "Block"
max_width = 100
newline_style = "Unix"
reorder_impl_items = true
reorder_imports = true
use_small_heuristics = "Max"