[package]
name = "untitled_rpg_toy"
version = "0.0.1"
edition = "2024"

[dependencies]
rand = "*"

[dependencies.bevy]
version = "0.16.*"
default-features = false
#features = [
#    "bevy_state",
#    "std",
#]
